name: Update project estimates

on:
  issues:
    types: [labeled, unlabeled]
  project_card:
    types: [moved, created]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Update project column estimates
    steps:
      - uses: actions/checkout@v1

      - name: actions/checkout@v1
        id: run
        uses: mathiasjakobsen/github-estimates-action@v0.1.0
        with:
          owner: 'manoranjith'
          repo: 'sample-repo-2'
          token: ${{ secrets.GITHUB_TOKEN }}
